# Generated by Django 5.0.6 on 2024-05-23 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_first_line', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('primary_phone_mobile', models.CharField(max_length=20)),
                ('other_contact_numbers', models.TextField(blank=True, null=True)),
                ('phone_landline', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cafe_logos/')),
                ('translation_required', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('post_box_number', models.CharField(blank=True, max_length=50, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_customers', models.PositiveIntegerField(default=0, verbose_name='total_customers')),
                ('total_credit', models.PositiveIntegerField(default=0, verbose_name='total_credit')),
                ('total_debit', models.PositiveIntegerField(default=0, verbose_name='total_debit')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='total_transactions')),
                ('transaction_statistics', models.JSONField(blank=True, default=list, null=True)),
                ('credit_statistics', models.JSONField(blank=True, default=list, null=True)),
                ('customer_statistics', models.JSONField(blank=True, default=list, null=True)),
                ('debit_statistics', models.JSONField(blank=True, default=list, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cafes', to='owner.owner')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
